title: "Yihong (程奕泓) Cheng"
name: "Yihong Cheng"
description: "STEM Education • Curriculum & Assessment • Educational Measurement"

url: "https://dr-yihongcheng.github.io"
baseurl: ""
include: [_pages]

future: true
timezone: Asia/Macau

# Use Minimal Mistakes via remote theme (disable default theme)
theme: null
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

author:
  name: "Yihong (程奕泓) Cheng"
  avatar: "/assets/img/profile.jpg"
  bio: "Assistant Professor, School of Education, City University of Macau. STEM education, curriculum & assessment, educational measurement."
  location: "Taipa, Macao"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yhcheng@cityu.edu.mo"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai-fw"
      url: "https://scholar.google.com/citations?hl=en&user=gYp1Q4IAAAAJ&view_op=list_works&sortby=pubdate"
    - label: "CV (PDF)"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/cv/Yihong_Cheng_CV.pdf"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      share: true
      comments: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

exclude:
  - node_modules
  - vendor
  - Gemfile.lock
  - README.md
  - LICENSE
